export interface CreateBooking{ 
    booking_no:string,
    pickup:string,
    dropoff:string,
    passenger:string,
    date:string,
    time:string,
    return_date:string,
    return_time:string,
    estimated_trip_time:string,
    distance:string,
    currency:string,
    vehicle_name:string,
    passengers_no:string,
    medium_bags:string,
    passenger_name:string,
    passenger_email:string,
    passenger_contact_no:string,
    planeArrivingFrom: string,
    airlineName: string,
    flightNumber: string,
    cruiseShipName: string,
    trainArrivingFrom: string,
    trainName: string,
    trainOperator: string,
    hotelName: string,
    venueAddress:string,
    gstNumber:string,
    gstRequired:string,
    pickupAddress: string,
    destinationName: string,
    destinationAddress: string,
    agentforeign:number
}

